// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT0Tth9RXraSiSdBdZy8CUaXLFrShm9i0',
    appId: '1:964981185799:web:a9f95586d1b7185194b9a2',
    messagingSenderId: '964981185799',
    projectId: 'fir-flutter-codelab-c8d65',
    authDomain: 'fir-flutter-codelab-c8d65.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-c8d65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgowX99kGQAFTOtkEOFJmONo3JFiytiPs',
    appId: '1:964981185799:android:05766e86ca0d8a8794b9a2',
    messagingSenderId: '964981185799',
    projectId: 'fir-flutter-codelab-c8d65',
    storageBucket: 'fir-flutter-codelab-c8d65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzCFYR80-vOC-Gn9di-U1WQYcYuzWkhbk',
    appId: '1:964981185799:ios:292d39ebba89a58194b9a2',
    messagingSenderId: '964981185799',
    projectId: 'fir-flutter-codelab-c8d65',
    storageBucket: 'fir-flutter-codelab-c8d65.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
    iosClientId: '964981185799-aj325bd6vvqct4fjdithp1ojvjosaivp.apps.googleusercontent.com', // 这里要有值

  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzCFYR80-vOC-Gn9di-U1WQYcYuzWkhbk',
    appId: '1:964981185799:ios:292d39ebba89a58194b9a2',
    messagingSenderId: '964981185799',
    projectId: 'fir-flutter-codelab-c8d65',
    storageBucket: 'fir-flutter-codelab-c8d65.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
